In [1]:
import pandas as pd

from Correlations_Distance_matrices_engine.data_loader import DataLoader
from Correlations_Distance_matrices_engine.correlation_distance_matrix_engine import CorrelationDistanceMatrixEngine

In [2]:
loader_data = DataLoader()
engine_computations = CorrelationDistanceMatrixEngine(loader_data)

### Data Preparations
## logarithmic returns splittings

In [3]:
engine_splits = engine_computations.splitter()
engine_splits[0]

,Industrial,Financials,Services,Property,Holding_Firms,Mining_and_Oil
Dates,,,,,,
2019-07-08,-0.016575,0.026500,-0.001186,0.010037,-0.005012,-0.000286
2019-07-15,-0.007367,0.048285,-0.007075,-0.000081,0.023527,0.088613
2019-07-22,-0.020453,-0.015455,-0.017885,-0.017440,0.007051,-0.031921
2019-07-29,-0.004861,0.006960,-0.023756,-0.005326,-0.012262,0.028864
2019-08-05,-0.054735,-0.005279,-0.013437,-0.053189,-0.034926,0.006245
2019-08-12,0.003700,-0.039836,-0.014391,-0.015497,0.012578,-0.012470
2019-08-19,0.013981,0.026527,0.013322,-0.005036,0.005876,0.002829
2019-08-26,0.011689,0.003366,0.021073,-0.004664,0.019155,0.021627
2019-09-02,-0.019172,-0.016006,-0.017871,0.013162,-0.001860,0.116448
2019-09-09,0.008840,0.015646,0.017785,0.003231,0.001321,0.034149
2019-09-16,-0.006651,-0.025443,-0.021648,-0.019459,-0.008814,-0.022823
2019-09-23,-0.035566,0.009454,-0.028615,0.020576,-0.016139,-0.044342
2019-09-30,-0.007555,0.001130,-0.021856,-0.014288,-0.022503,-0.014073
2019-10-07,0.018920,0.008592,0.010326,0.029184,0.015609,0.037214
2019-10-14,-0.003224,0.010971,0.002572,0.011453,0.000848,-0.029972
2019-10-21,-0.016383,0.019113,0.000836,-0.002627,0.008838,0.033329
2019-10-28,0.000083,0.021929,-0.012140,0.001439,0.010948,0.000791
2019-11-04,0.000706,0.014670,0.025391,-0.000336,0.013071,-0.013536
2019-11-11,-0.038524,-0.013394,-0.002897,-0.012315,-0.015613,-0.039307
2019-11-18,-0.017078,-0.024623,0.001440,-0.021249,-0.006872,-0.067022
2019-11-25,-0.013236,-0.017401,-0.002080,0.002570,-0.016442,-0.014956

In [4]:
engine_splits[1]

,Industrial,Financials,Services,Property,Holding_Firms,Mining_and_Oil
Dates,,,,,,
2019-12-02,-0.023362,0.017657,-0.030950,0.013822,0.015654,-0.068943
2019-12-09,0.017290,0.015120,0.017087,0.022683,-0.015277,0.000525
2019-12-16,-0.037144,-0.032039,0.005329,-0.013056,-0.004419,0.008642
2019-12-23,0.028154,0.011055,-0.001462,0.003612,-0.000998,0.064471
2019-12-30,0.005080,-0.010340,0.010506,0.004599,0.005209,-0.008840
2020-01-06,-0.033566,-0.009238,0.005408,-0.014804,0.000489,0.010774
2020-01-13,0.011988,0.010554,0.005360,-0.018793,-0.021159,0.004417
2020-01-20,0.026170,-0.019983,-0.012456,-0.018370,-0.017166,-0.021766
2020-01-27,-0.086625,-0.048345,-0.046037,-0.031686,-0.062911,-0.039020
2020-02-03,0.051367,0.037638,0.018610,0.050308,0.034988,-0.037194
2020-02-10,-0.049665,-0.029543,-0.042525,-0.027156,-0.013247,-0.044991
2020-02-17,0.005628,-0.000017,0.003126,0.004090,0.023407,0.003996
2020-02-24,-0.073349,-0.079524,-0.066852,-0.082277,-0.085549,-0.093945
2020-03-02,-0.028839,-0.006096,-0.015541,0.014127,-0.002239,-0.026661
2020-03-09,-0.137582,-0.120049,-0.113642,-0.210502,-0.153093,-0.284180
2020-03-16,-0.160490,-0.196000,-0.134927,-0.190192,-0.209329,-0.232915
2020-03-23,0.029754,0.045023,0.126182,0.119323,0.110959,0.091042
2020-03-30,0.036310,-0.027906,0.009830,0.015346,0.023716,0.038119
2020-04-06,0.094716,-0.022563,0.027657,0.005030,0.045528,0.013770
2020-04-13,0.067466,0.065504,0.057702,0.043195,0.039308,0.081575
2020-04-20,-0.048376,-0.038802,0.004415,-0.087474,-0.066720,-0.020639
2020-04-27,0.036158,-0.000017,0.054793,0.073280,0.033473,0.024971
2020-05-04,-0.020017,-0.034744,-0.037935,0.004456,-0.002170,-0.040684
2020-05-11,0.024254,-0.016404,-0.006554,-0.033457,-0.017354,-0.003406
2020-05-18,-0.027259,-0.024106,0.006138,-0.008047,0.018830,-0.008965
2020-05-25,0.000859,0.064896,0.030033,-0.010622,0.070732,-0.023234

### Correlation Matrix Construction
## Batch A and Batch B

In [5]:
batch_corr = [pd.DataFrame(), pd.DataFrame()]
batch_dist = [pd.DataFrame(), pd.DataFrame()]
batch_corr[0], batch_corr[1], batch_dist[0], batch_dist[1] = engine_computations.make_yields_splitter(engine_splits)

In [6]:
batch_corr[0]

,Industrial,Financials,Services,Property,Holding_Firms,Mining_and_Oil
Industrial,1.000000,0.238850,0.515451,0.447992,0.700198,0.226856
Financials,0.238850,1.000000,0.323370,0.400291,0.353456,0.383701
Services,0.515451,0.323370,1.000000,0.206448,0.492794,0.061083
Property,0.447992,0.400291,0.206448,1.000000,0.427269,0.289601
Holding_Firms,0.700198,0.353456,0.492794,0.427269,1.000000,0.360937
Mining_and_Oil,0.226856,0.383701,0.061083,0.289601,0.360937,1.000000

In [7]:
batch_corr[1]

,Industrial,Financials,Services,Property,Holding_Firms,Mining_and_Oil
Industrial,1.000000,0.791948,0.810939,0.807057,0.829582,0.812976
Financials,0.791948,1.000000,0.837813,0.843601,0.898150,0.792531
Services,0.810939,0.837813,1.000000,0.873163,0.893512,0.876838
Property,0.807057,0.843601,0.873163,1.000000,0.919990,0.868430
Holding_Firms,0.829582,0.898150,0.893512,0.919990,1.000000,0.834165
Mining_and_Oil,0.812976,0.792531,0.876838,0.868430,0.834165,1.000000

### Distance Matrix
## Batch A and Batch B

In [8]:
batch_dist[0]

,Industrial,Financials,Services,Property,Holding_Firms,Mining_and_Oil
Industrial,0.000000,1.233815,0.984428,1.050722,0.774341,1.243498
Financials,1.233815,0.000000,1.163297,1.095179,1.137140,1.110224
Services,0.984428,1.163297,0.000000,1.259803,1.007180,1.370341
Property,1.050722,1.095179,1.259803,0.000000,1.070263,1.191972
Holding_Firms,0.774341,1.137140,1.007180,1.070263,0.000000,1.130542
Mining_and_Oil,1.243498,1.110224,1.370341,1.191972,1.130542,0.000000

In [9]:
batch_dist[1]

,Industrial,Financials,Services,Property,Holding_Firms,Mining_and_Oil
Industrial,0.000000,0.645062,0.614916,0.621197,0.583811,0.611595
Financials,0.645062,0.000000,0.569539,0.559283,0.451331,0.644156
Services,0.614916,0.569539,0.000000,0.503660,0.461494,0.496310
Property,0.621197,0.559283,0.503660,0.000000,0.400026,0.512972
Holding_Firms,0.583811,0.451331,0.461494,0.400026,0.000000,0.575908
Mining_and_Oil,0.611595,0.644156,0.496310,0.512972,0.575908,0.000000