In [14]:
from itertools import combinations
from sage.all import Graph
from sage.all import matrix
from sage.all import RDF
import matplotlib.pyplot as plt

import pandas as pd
from Correlations_Distance_matrices_engine.data_loader import DataLoader
from Correlations_Distance_matrices_engine.correlation_distance_matrix_engine import CorrelationDistanceMatrixEngine

### Setup
## Loading Data and matrix computations

In [15]:
loader_data = DataLoader()
engine_computations = CorrelationDistanceMatrixEngine(loader_data)
engine_splits = engine_computations.splitter()
batch_corr = [pd.DataFrame(), pd.DataFrame()]
batch_dist = [pd.DataFrame(), pd.DataFrame()]
batch_corr[0], batch_corr[1], batch_dist[0], batch_dist[1] = engine_computations.make_yields_splitter(engine_splits)

## Visualizing matrices
# batch a correlation matrix

In [16]:
batch_corr[0]

,Services,Financials,Mining_and_Oil,Holding_Firms,Industrial,Property
Services,1.000000,0.323370,0.061083,0.492794,0.515451,0.206448
Financials,0.323370,1.000000,0.383701,0.353456,0.238850,0.400291
Mining_and_Oil,0.061083,0.383701,1.000000,0.360937,0.226856,0.289601
Holding_Firms,0.492794,0.353456,0.360937,1.000000,0.700198,0.427269
Industrial,0.515451,0.238850,0.226856,0.700198,1.000000,0.447992
Property,0.206448,0.400291,0.289601,0.427269,0.447992,1.000000

# batch b correlation matrix

In [17]:
batch_corr[1]

,Services,Financials,Mining_and_Oil,Holding_Firms,Industrial,Property
Services,1.000000,0.837813,0.876838,0.893512,0.810939,0.873163
Financials,0.837813,1.000000,0.792531,0.898150,0.791948,0.843601
Mining_and_Oil,0.876838,0.792531,1.000000,0.834165,0.812976,0.868430
Holding_Firms,0.893512,0.898150,0.834165,1.000000,0.829582,0.919990
Industrial,0.810939,0.791948,0.812976,0.829582,1.000000,0.807057
Property,0.873163,0.843601,0.868430,0.919990,0.807057,1.000000

# batch a distance matrix

In [18]:
batch_dist[0]

,Services,Financials,Mining_and_Oil,Holding_Firms,Industrial,Property
Services,0.000000,1.163297,1.370341,1.007180,0.984428,1.259803
Financials,1.163297,0.000000,1.110224,1.137140,1.233815,1.095179
Mining_and_Oil,1.370341,1.110224,0.000000,1.130542,1.243498,1.191972
Holding_Firms,1.007180,1.137140,1.130542,0.000000,0.774341,1.070263
Industrial,0.984428,1.233815,1.243498,0.774341,0.000000,1.050722
Property,1.259803,1.095179,1.191972,1.070263,1.050722,0.000000

# batch b distance matrix

In [19]:
batch_dist[1]

,Services,Financials,Mining_and_Oil,Holding_Firms,Industrial,Property
Services,0.000000,0.569539,0.496310,0.461494,0.614916,0.503660
Financials,0.569539,0.000000,0.644156,0.451331,0.645062,0.559283
Mining_and_Oil,0.496310,0.644156,0.000000,0.575908,0.611595,0.512972
Holding_Firms,0.461494,0.451331,0.575908,0.000000,0.583811,0.400026
Industrial,0.614916,0.645062,0.611595,0.583811,0.000000,0.621197
Property,0.503660,0.559283,0.512972,0.400026,0.621197,0.000000

### Graph Visualizations
## Baseline Complete Graph

In [20]:
sectors = ["Property", "Mining & Oil", "Financials", "Holding Firms", "Industrial", "Services"]
K6 = Graph()
K6.add_vertices(sectors)
K6.add_edges(combinations(sectors, 2))

for u, v, _ in K6.edges():
    K6.set_edge_label(u,v, "{:.2f}".format(0.00))

K6.show(figsize=8, edge_labels=True, layout='circular')
K6.plot(figsize=8, edge_labels=True, layout='circular').save("CompleteGraph.png")

Graphics object consisting of 37 graphics primitives

![Complete_Graph](CompleteGraph.png)

## Correlations weighted Complete Graph
# batch a

In [21]:
corr_matrix_batch_a = matrix(RDF,6,6, batch_corr[0].values)
K6_batch_a_corr = Graph(corr_matrix_batch_a, format="adjacency_matrix", vertex_labels=sectors)
K6_batch_a_corr.remove_loops()
mapping_a = {i: sectors[i] for i in range(6)}
K6_batch_a_corr.relabel(mapping_a)
K6_batch_a_corr.show(figsize=8, edge_labels=True, layout='circular')
K6_batch_a_corr.plot(figsize=8, edge_labels=True, layout='circular').save("CompleteGraph_batch_a_corr.png")

Graphics object consisting of 37 graphics primitives

![batch_a_corr](CompleteGraph_batch_a_corr.png)

# batch b

In [22]:
corr_matrix_batch_b = matrix(RDF,6,6,batch_corr[1].values)
K6_batch_b_corr = Graph(corr_matrix_batch_b, format="adjacency_matrix", vertex_labels=sectors)
K6_batch_b_corr.remove_loops()
mapping_b = {i: sectors[i] for i in range(6)}
K6_batch_b_corr.relabel(mapping_b)
K6_batch_b_corr.show(figsize=8, edge_labels=True, layout='circular')
K6_batch_b_corr.plot(figsize=8, edge_labels=True, layout='circular').save("CompleteGraph_batch_b_corr.png")

Graphics object consisting of 37 graphics primitives

![batch_b_corr](CompleteGraph_batch_b_corr.png)

## Distance weighted Complete Graph
# batch a

In [23]:
dist_matrix_batch_a = matrix(RDF,6,6, batch_dist[0].values)
K6_batch_a_dist = Graph(dist_matrix_batch_a, format="adjacency_matrix", vertex_labels=sectors)
K6_batch_a_dist.remove_loops()
mapping_a_dist = {i: sectors[i] for i in range(6)}
K6_batch_a_dist.relabel(mapping_a_dist)
K6_batch_a_dist.show(figsize=8, edge_labels=True, layout='circular')
K6_batch_a_dist.plot(figsize=8, edge_labels=True, layout='circular').save("CompleteGraph_batch_a_dist.png")

Graphics object consisting of 37 graphics primitives

![batch_a_dist](CompleteGraph_batch_a_dist.png)

# batch b

In [24]:
dist_matrix_batch_b = matrix(RDF,6,6,batch_dist[1].values)
K6_batch_b_dist = Graph(dist_matrix_batch_b, format="adjacency_matrix", vertex_labels=sectors)
K6_batch_b_dist.remove_loops()
mapping_b_dist = {i: sectors[i] for i in range(6)}
K6_batch_b_dist.relabel(mapping_b_dist)
K6_batch_b_dist.show(figsize=8, edge_labels=True, layout='circular')
K6_batch_b_dist.plot(figsize=8, edge_labels=True, layout='circular').save("CompleteGraph_batch_b_dist.png")

Graphics object consisting of 37 graphics primitives

![batch_b_dist](CompleteGraph_batch_b_dist.png)

## Minimum Spanning Tree via Kruskal's Algorithm
# batch a

In [25]:
K6_batch_a_dist_copy = K6_batch_a_dist
K6_batch_a_dist_copy_mst_edges = K6_batch_a_dist_copy.min_spanning_tree(algorithm="Kruskal")
K6_batch_a_dist_mst = Graph(K6_batch_a_dist_copy_mst_edges,weighted=True)
K6_batch_a_dist_mst.show(figsize=8, edge_labels=True, layout='spring', edge_color='red')
K6_batch_a_dist_mst.plot(figsize=8, edge_labels=True, layout='spring').save("CompleteGraph_batch_a_dist_mst.png")

Graphics object consisting of 17 graphics primitives

![batch_a_mst](CompleteGraph_batch_a_dist_mst.png)

# batch b

In [26]:
K6_batch_b_dist_copy = K6_batch_b_dist
K6_batch_b_dist_copy_mst_edges = K6_batch_b_dist_copy.min_spanning_tree(algorithm="Kruskal")
K6_batch_b_dist_mst = Graph(K6_batch_b_dist_copy_mst_edges,weighted=True)
K6_batch_b_dist_mst.show(figsize=8, edge_labels=True, layout='spring', edge_color='red')
K6_batch_b_dist_mst.plot(figsize=8, edge_labels=True, layout='spring').save("CompleteGraph_batch_b_dist_mst.png")

Graphics object consisting of 17 graphics primitives

![batch_b_mst](CompleteGraph_batch_b_dist_mst.png)